language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install . pytest mock codecov
  - pip install -e .

script:
  - coverage run --source iawscli -m py.test

after_success:
  - codecov